/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#192540',
        'surface-dim': '#060e20',
        'primary': '#a3a6ff',
        'surface': '#060e20',
        'on-primary': '#0f00a4',
        'error': '#ff6e84',
        'secondary-dim': '#9c48ea',
        'outline-variant': '#40485d',
        'surface-container-lowest': '#000000',
        'surface-container-high': '#141f38',
        'on-background': '#dee5ff',
        'outline': '#6d758c',
        'tertiary': '#61c2ff',
        'background': '#060e20',
        'surface-tint': '#a3a6ff',
        'surface-variant': '#192540',
        'on-surface': '#dee5ff',
        'secondary': '#c180ff',
        'primary-dim': '#6063ee',
        'primary-fixed-dim': '#8387ff',
        'secondary-container': '#6f00be',
        'tertiary-dim': '#17a8ec',
        'on-secondary-container': '#e9cdff',
        'surface-container-low': '#091328',
        'tertiary-container': '#34b5fa',
        'on-surface-variant': '#a3aac4',
        'on-secondary': '#33005b',
        'surface-container': '#0f1930',
        'primary-container': '#9396ff',
        'primary-fixed': '#9396ff',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
